spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mywatchlist
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request:size: 5MB

application:
  tmdb:
    api-key: ${TMDB_API_KEY}
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 2592000000
  upload:
    dir: uploads/avatars
    base-url: http://localhost:8080/uploads/avatars
